version: '3.7'

services:
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER1: ${MYSQL_USER1}
      MYSQL_USER1_PASSWORD: ${MYSQL_USER1_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      retries: 10

  redis:
    build: ./requirements/redis/.
    container_name: redis
    image: redis
    networks:
      - inception_network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      retries: 10
  
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    image: wordpress
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER1: ${MYSQL_USER1}
      MYSQL_USER1_PASSWORD: ${MYSQL_USER1_PASSWORD}
      
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WORDPRESS_ADMIN_NAME: ${WORDPRESS_ADMIN_NAME}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}

      WORDPRESS_USER1: ${WORDPRESS_USER1}
      WORDPRESS_USER1_EMAIL: ${WORDPRESS_USER1_EMAIL}
      WORDPRESS_USER1_PASSWORD: ${WORDPRESS_USER1_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/html
      - ssl-volume:/etc/nginx/ssl/
    networks:
      - inception_network
    depends_on:
      - wordpress
  
  ftp-server:
    build: ./requirements/ftp-server/.
    container_name: ftp-server
    image: ftp-server
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
      - 0.0.0.0:20000-22000:20000-22000
    volumes:
      - ssl-volume:/etc/nginx/ssl/
      - wp-volume:/var/www/html
    networks:
      - inception_network
    depends_on:
      - nginx

networks:
  inception_network:
    driver: bridge
    name: inception_network

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      device: ~/home/qdo/data/wp_vol14
      o: bind
  wp-volume:
    driver: local
    driver_opts:
      type: none
      device: ~/home/qdo/data/mdb_vol14
      o: bind
  
  ssl-volume:

