version: '3.7'

services:
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      retries: 10

  redis:
    build: ./requirements/redis/.
    container_name: redis
    image: redis
    networks:
      - inception_network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      retries: 10
  
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    image: wordpress
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

  adminer:
    build: ./requirements/adminer/.
    container_name: adminer
    image: adminer
    volumes:
      - wp-volume:/var/www/html
    ports:
      - "8080:8080"
    networks:
      - inception_network
    depends_on:
      - wordpress

  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/html
      - ssl-volume:/etc/nginx/ssl/
    networks:
      - inception_network
    depends_on:
      - wordpress
  
  wps-hide-login:
    build: ./requirements/wps-hide-login/.
    container_name: wps-hide-login
    image: wps-hide-login
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
  
  ftp-server:
    build: ./requirements/ftp-server/.
    container_name: ftp-server
    image: ftp-server
    env_file:
      - .env
    ports:
      - "20:20"
      - "21:21"
      - 20000-20050:20000-20050
    volumes:
      - ssl-volume:/etc/nginx/ssl/
      - wp-volume:/var/www/html
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge
    name: inception_network

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/qdo/data/wp_volasd2
      o: bind
  wp-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/qdo/data/mdb_volasd2
      o: bind
  
  ssl-volume: