FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y && apt-get install wget -y

# download, save as latest.php
RUN mkdir -p /var/www/html/
RUN wget https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php -O adminer.php
COPY run.sh /run.sh
RUN chmod 744 /run.sh

# In here, we access wordpress already, just need to access mariadb -> done
# Datenbank System	 MySQL 
# Server	 mariadb 
# Benutzer	 mysql_user1
# Passwort	 •••• 
# Datenbank	 database1

CMD ["/run.sh"]

