FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y && apt-get install wget -y

# download, save as latest.php
RUN mkdir -p /var/www/html/
RUN wget https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php -O adminer.php
COPY run.sh /run.sh
RUN chmod 744 /run.sh

CMD ["/run.sh"]

